print("Enter your first number:")
inpnum1 = input()
print("You Entered first number.")
print("Enter second number now:")
inpnum2 = input()
print("You entered second number")
print("Sum of these numbers is:", int(inpnum1) + int(inpnum2))
